### ISSUE TITLE
srsly.write_json segfaults trying to write numpy types

### ISSUE THREAD

**Issue by jjjamie** [explosion/srsly#30]
Hi,

I was using srsly for json serialization and it killed my jupyter kernels without producing any errors. It turns out it's due to ujson segmentation faults trying to serialize types it doesn't understand. It's quite easy to reproduce though:

```
import numpy as np
import srsly
f = np.float32()
srsly.write_json("x.json", f)
```

Believe this has now been fixed in ujson as part of https://github.com/ultrajson/ultrajson/commit/53f85b1bd6e4f27a3e4cdc605518c48a6c7e7e9e (issue https://github.com/ultrajson/ultrajson/issues/294). Doing an equivalent test with the latest ujson (version 3.0) gives a sensible error.

Prior to that fix, it looked like some people were abandoning ujson (https://github.com/noirbizarre/flask-restplus/issues/589) and there was a Pandas fork (https://github.com/pandas-dev/pandas/tree/master/pandas/_libs/src/ujson/python) before it started being maintained again.

Are there any plans to update the version used by srsly?

**Comment by honnibal** [comment]
Thanks for the report, yes we'll update the vendored code.

**Comment by dshefman1** [comment]
I had the same situation where srsly.write_json kills the kernel, instead of reporting an error message. Here is an example that causes the error every time on my machine:

```
from pathlib import Path
import srsly

srsly.write_json('foobar.json', {'foobar': [Path('./foo'), Path('/bar')]})
```
Error message from Pycharm: "Process finished with exit code -1073741819 (0xC0000005)"

Error message from Jupyter Lab: "Kernal Restarting. The kernel appears to have died. It will restart automatically."
