### ISSUE TITLE
is_yaml_serializable giving alternating answers for same object

### ISSUE THREAD

**Issue by dcwil** [explosion/srsly#55]
I encountered this problem while writing a custom saving loop that utilises srsly. Here is an example:

```
import srsly
import numpy as np

data = {
    1: np.ones([10, 10]),
    2: np.zeros([50, 50])
}

assert srsly.is_yaml_serializable(data) == srsly.is_yaml_serializable(data)
```

will trigger the assertion error. 

Even successively running `srsly.is_yaml_serializable(data)` in the console will result in the answer flipping between True/False with every iteration.

**Comment by polm** [comment]
Thanks for the report! This is really weird behavior, and seems to be a bug with the underlying yaml serializer. 

It looks like what happens it that it alternately throws an error or returns a string consistent of a single space. The input data doesn't seem to change, so this must be related to some kind of internal state. 

Also, this only happens if the numpy data is in a dictionary - if you try to serialize the array directly it will consistently throw an error. 

We'll look at why this is happening.
