### ISSUE TITLE
Update Ultrajson

### ISSUE THREAD

**Issue by AsymptoticBrain** [explosion/srsly#61]
Hi, 

Ultrajson recently got updated, I'm uncertain how it works with forks and srsly being standalone but is it possible to update the version used in srsly to use this latest version?

//Tim

**Comment by svlandeg** [comment]
Thanks for the note, we'll definitely have a look!

**Comment by adrianeboyd** [comment]
So far we've just ported changes as needed. Aside from the security vulnerability, are there any other updates that are relevant to you? Since it's not in the standard, my initial preference would be to leave out the `NaN` and `Infinity` changes. We have had users running into issues accidentally trying to serialize `NaN`, but usually it's because of another bug, not something that our users need to do with `srsly` in general.

**Comment by AsymptoticBrain** [comment]
No, it was mainly the security issue that was flagged and I wanted to get rid off.
