### ISSUE TITLE
Unable to import srsly.ujson.ujson for SpaCy -- AWS Lambda

### ISSUE THREAD

**Issue by nagarajanshanmuganthan** [explosion/srsly#8]
I am trying to add SpaCy as a dependency to my Python Lambda. I am doing this by installing SpaCy as a standalone dependency inside a directory named `dependencies` using `pip3 install spacy --no-deps -t .` This is because I can't load the entire Spacy dependency inside the `\tmp` directory of my Lambda. 

I am able to successfully upload the folder to s3 and download it during the Lambda invocation. When I try to `import spacy`, I get this error: `[ERROR] Runtime.ImportModuleError: Unable to import module : No module named 'srsly.ujson.ujson'`. 

I manually installed `srsly` inside `dependencies\` and I have all the files that are listed as per [this link][1]. This was referenced by [this link][2]. One of the responses says, "it seems like Python can't load it, because it's not compiled?". How would I compile a dependency which has a `.c` file in it?

One other question which I found on SO is [this question][3], but I have already manually installed `srsly`. How to I import the module? Thanks.

--- 

I manually check in my code for the presence of `ujson` before importing spacy like this:

```python
if os.path.exists('/tmp/dependencies/srsly/ujson/ujson.c'):
    print('ujson exists')
```

and the print statement gets printed. 

  [1]: https://github.com/explosion/srsly/tree/master/srsly/ujson
  [2]: https://github.com/explosion/srsly/issues/3
  [3]: https://stackoverflow.com/questions/56895324/not-able-to-import-en-core-web-sm-or-spacy

**Comment by nagarajanshanmuganthan** [comment]
@ines I have also commented on the other ticket and decided to provide full information here.

**Comment by honnibal** [comment]
Your problem here comes down to some details of how Python imports work. spaCy, srsly, and most of the rest of the dependency chain makes use of compiled modules. You can't import from the ujson.c file. Instead there needs to be some `.so` file.

Those `.so` files are named in a way that specifies the Python version and platform, so that you can have multiple shared objects in the same directory, for different versions. I think what's happening is that you're not uploading a version with shared objects AWS lambda can use.

I don't know what the best way to solve your problem will be, but I expect the same problem will occur with any other Python compiled module.

One solution that may or may not work could be to use the `.pex` compilation method I have in the spaCy repo. If you just clone the spaCy repo and run `make`, you'll get a self-contained executable `dist/spacy.pex`. This might be a good target to upload to AWS lambda, although you'd need to ensure you have the same Python version in the same location as the Lambda instance.

Making your project work on AWS Lambda is not something we can support directly, however. Please contact AWS support for help, as I don't think the problems relate to our code specifically.
